/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package core;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

import parser.ExprLexer;
import parser.ExprParser;

public class App {

    public static void main(String[] args) {
        // CharStream input = CharStreams.fromString("2*3+4*5");
        if (args == null) {
            System.err.println("args == NULL");
            return;
        }
        CharStream input = CharStreams.fromString(args[0]);
        ExprLexer exprLexer = new ExprLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(exprLexer);
        ExprParser parser = new ExprParser(tokens);
        ParseTree tree = parser.stat();
        ParseTreeWalker walker = new ParseTreeWalker(); // create standard walker

        GenCoder evaluator = new GenCoder();
        walker.walk(evaluator, tree);

    }

}
