/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package core;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;

import core.ast.Exp;
import core.ast.NodeKind;
import parser.ExprLexer;
import parser.ExprParser;

public class App {

    public static void main(String[] args) {
        // CharStream input = CharStreams.fromString("- -10");
        if (args == null) {
            System.err.println("args == NULL");
            return;
        }
        CharStream input = CharStreams.fromString(args[0]);
        ExprLexer exprLexer = new ExprLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(exprLexer);
        ExprParser parser = new ExprParser(tokens);
        ParseTree tree = parser.stat();
        BuildAst makeAst = new BuildAst();
        Exp ast = makeAst.visit(tree);
        System.out.println(".intel_syntax noprefix");
        System.out.println(".globl main");
        System.out.println("main:");
        gen(ast);
        System.out.println("  pop rax");
        System.out.println("  ret");
    }

    private static void gen(Exp exp) {
        if (exp.getKind() == NodeKind.ND_NUM) {
            System.out.println("  push " + exp.getValue());
            return;
        }
        gen(exp.getLeft());
        gen(exp.getRight());
        System.out.println("  pop rdi");
        System.out.println("  pop rax");
        switch (exp.getKind()) {
            case ND_ADD:
                System.out.println("  add rax, rdi");
                break;
            case ND_SUB:
                System.out.println("  sub rax, rdi");
                break;
            case ND_MUL:
                System.out.println("  imul rax, rdi");
                break;
            case ND_DIV:
                System.out.println("  cqo");
                System.out.println("  idiv rdi");
                break;
            case ND_EQ:
                System.out.println("  cmp rax, rdi");
                System.out.println("  sete al");
                System.out.println("  movzb rax, al");
                break;
            case ND_NE:
                System.out.println("  cmp rax, rdi");
                System.out.println("  setne al");
                System.out.println("  movzb rax, al");
                break;
            case ND_LESS:
                System.out.println("  cmp rax, rdi");
                System.out.println("  setl al");
                System.out.println("  movzb rax, al");
                break;
            case ND_LESS_EQ:
                System.out.println("  cmp rax, rdi");
                System.out.println("  setle al");
                System.out.println("  movzb rax, al");
                break;
            case ND_MORE:
                System.out.println("  cmp rdi, rax");
                System.out.println("  setl al");
                System.out.println("  movzb rax, al");
                break;
            case ND_MORE_EQ:
                System.out.println("  cmp rdi, rax");
                System.out.println("  setle al");
                System.out.println("  movzb rax, al");
            default:
                break;
        }
        System.out.println("  push rax");
    }

}
